export const employeeData = [
    {
      EmployeeId: 1,
      EmployeeType: 'Full-time',
      EmployeeName: 'John Doe',
      CellNo: '123-456-7890',
      EmailId: 'john.doe@example.com',
      Status: 'Active',
    },
    {
      EmployeeId: 2,
      EmployeeType: 'Part-time',
      EmployeeName: 'Jane Smith',
      CellNo: '987-654-3210',
      EmailId: 'jane.smith@example.com',
      Status: 'Inactive',
    },
    {
      EmployeeId: 3,
      EmployeeType: 'Contractor',
      EmployeeName: 'Mike Johnson',
      CellNo: '555-555-5555',
      EmailId: 'mike.johnson@example.com',
      Status: 'Active',
    },
    {
      EmployeeId: 4,
      EmployeeType: 'Full-time',
      EmployeeName: 'Emily Brown',
      CellNo: '111-222-3333',
      EmailId: 'emily.brown@example.com',
      Status: 'Active',
    },
    {
      EmployeeId: 5,
      EmployeeType: 'Intern',
      EmployeeName: 'Alex Wilson',
      CellNo: '444-444-4444',
      EmailId: 'alex.wilson@example.com',
      Status: 'Active',
    },
    {
      EmployeeId: 6,
      EmployeeType: 'Full-time',
      EmployeeName: 'Sarah Miller',
      CellNo: '777-888-9999',
      EmailId: 'sarah.miller@example.com',
      Status: 'Inactive',
    },
    {
      EmployeeId: 7,
      EmployeeType: 'Part-time',
      EmployeeName: 'Michael Lee',
      CellNo: '222-333-4444',
      EmailId: 'michael.lee@example.com',
      Status: 'Active',
    },
    {
      EmployeeId: 8,
      EmployeeType: 'Full-time',
      EmployeeName: 'Jessica Davis',
      CellNo: '666-777-8888',
      EmailId: 'jessica.davis@example.com',
      Status: 'Active',
    },
    {
      EmployeeId: 9,
      EmployeeType: 'Contractor',
      EmployeeName: 'David Clark',
      CellNo: '888-888-8888',
      EmailId: 'david.clark@example.com',
      Status: 'Inactive',
    },
    {
      EmployeeId: 10,
      EmployeeType: 'Full-time',
      EmployeeName: 'Olivia White',
      CellNo: '333-444-5555',
      EmailId: 'olivia.white@example.com',
      Status: 'Active',
    },
    {
        EmployeeId: 11,
        EmployeeType: 'Part-time',
        EmployeeName: 'William Turner',
        CellNo: '777-111-2222',
        EmailId: 'william.turner@example.com',
        Status: 'Active',
      },
      {
        EmployeeId: 12,
        EmployeeType: 'Full-time',
        EmployeeName: 'Sophia Adams',
        CellNo: '555-666-7777',
        EmailId: 'sophia.adams@example.com',
        Status: 'Inactive',
      },
      {
        EmployeeId: 13,
        EmployeeType: 'Intern',
        EmployeeName: 'Ethan Martinez',
        CellNo: '444-555-6666',
        EmailId: 'ethan.martinez@example.com',
        Status: 'Active',
      },
      {
        EmployeeId: 14,
        EmployeeType: 'Full-time',
        EmployeeName: 'Ava Walker',
        CellNo: '888-999-0000',
        EmailId: 'ava.walker@example.com',
        Status: 'Active',
      },
      {
        EmployeeId: 15,
        EmployeeType: 'Contractor',
        EmployeeName: 'Daniel Cooper',
        CellNo: '123-321-1234',
        EmailId: 'daniel.cooper@example.com',
        Status: 'Inactive',
      },
      {
        EmployeeId: 16,
        EmployeeType: 'Full-time',
        EmployeeName: 'Mia Taylor',
        CellNo: '234-567-8901',
        EmailId: 'mia.taylor@example.com',
        Status: 'Active',
      },
      {
        EmployeeId: 17,
        EmployeeType: 'Part-time',
        EmployeeName: 'James Turner',
        CellNo: '345-678-9012',
        EmailId: 'james.turner@example.com',
        Status: 'Active',
      },
      {
        EmployeeId: 18,
        EmployeeType: 'Full-time',
        EmployeeName: 'Charlotte Wright',
        CellNo: '456-789-0123',
        EmailId: 'charlotte.wright@example.com',
        Status: 'Active',
      },
      {
        EmployeeId: 19,
        EmployeeType: 'Intern',
        EmployeeName: 'Liam Rodriguez',
        CellNo: '567-890-1234',
        EmailId: 'liam.rodriguez@example.com',
        Status: 'Inactive',
      },
      {
        EmployeeId: 20,
        EmployeeType: 'Full-time',
        EmployeeName: 'Amelia Harris',
        CellNo: '678-901-2345',
        EmailId: 'amelia.harris@example.com',
        Status: 'Active',
      },
  ];
  