export const components = [
    { "927": "Dashboard" },
    { "135": "User Settings" },
    { "864": "Company Settings" },
    { "549": "Company Configuration" },
    { "703": "Company Master" },
    { "872": "Financial Year Master" },
    { "287": "Bank Master" },
    { "610": "Cost Center Master" },
    { "954": "Department Master" },
    { "736": "Three Field Master" },
    { "624": "Two Field Master" },
    { "368": "HRM" },
    { "431": "Employee Settings" },
    { "217": "Employee Master" },
    { "820": "Employee Type Master" },
    { "598": "Employee Grade Master" },
    { "143": "Designation Master" },
    { "502": "KRA Master" },
    { "395": "Job Responsibility Master" },
    { "786": "Employee Band Master" },
    { "619": "Attendance Settings" },
    { "875": "Job Type Master" },
    { "752": "Shift Master" },
    { "201": "Weekly Off Master" },
    { "409": "Holiday Master" },
    { "148": "Attendance Device Master" },
    { "924": "Payroll Management" },
    { "269": "Earning Heads Master" },
    { "370": "Deduction Heads Master" },
    { "548": "Employee Type Earning Master" },
    { "753": "Employee Type Deduction Master" },
    { "654": "Professional Tax Setting" },
    { "531": "Advance Request" },
    { "317": "Advance Approval" },
    { "497": "Advance Repayment" },
    { "803": "Leaves Management" },
    { "460": "Leave Type Master" },
    { "706": "Leave Balance Upload" },
    { "153": "Leave Application" },
    { "418": "Leave Approvals" },
    { "849": "Attendance Management" },
    { "273": "Shift Roster" },
    { "159": "Manual Attendance Entry" },
    { "523": "Manual Attendance Approval" },
    { "926": "Out Door Duty Attendance Entry" },
    { "832": "Out Door Duty Attendance Approval" },
    { "871": "Employee Gate Pass Entry" },
    { "619": "Employee Gate Pass Approval" },
    { "625": "Job Allocation" },
    { "758": "Daily Attendance Processing" },
    { "690": "Attendance Import" },
    { "907": "Monthly Attendance Processing" },
    { "236": "Salary Management" },
    { "879": "Daily Overtime Processing" },
    { "182": "Monthly Overtime Processing" },
    { "305": "Overtime Approvals" },
    { "724": "Advance Management" },
    { "407": "Earning-Deduction Imports" },
    { "603": "Salary Processing" },
    { "141": "Salary Corrections" },
    { "980": "Registers" },
    { "593": "Master Register" },
    { "581": "Allocations" },
    { "465": "Finance" },
    { "819": "Projects" },
    { "280": "Purchase" },
    { "629": "Store" },
    { "972": "Sales" }
  ]
  